[package]
name = "holidays-ru-python"
version = "0.2.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"
repository = "https://github.com/hexqnt/holidays-ru"
description = "Python bindings for holidays-ru."

[lib]
name = "_holidays_ru"
crate-type = ["cdylib"]

[dependencies]
holidays-ru = { path = "../..", version = "0.2.1" }
holidays-ru-bindings-common = { path = "../common" }
pyo3 = { version = "0.29", features = ["abi3-py311"] }
